Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'System.Double'. Path '[11].transform.position.x'. ---> System.InvalidCastException: Null object cannot be converted to a value type.    at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)    at Newtonsoft.Json.Linq.JToken.ToObject[T]()    at MixItUp.Desktop.Services.StreamlabsOBSService.<GetArrayResult>d__23`1.MoveNext() in S:\Code\mixer-mixitup\MixItUp.Desktop\Services\StreamlabsOBSService.cs:line 320    at MixItUp.Desktop.Services.StreamlabsOBSService.<GetSceneItem>d__21.MoveNext() in S:\Code\mixer-mixitup\MixItUp.Desktop\Services\StreamlabsOBSService.cs:line 294    at MixItUp.Desktop.Services.StreamlabsOBSService.<SetSourceVisibility>d__13.MoveNext() in S:\Code\mixer-mixitup\MixItUp.Desktop\Services\StreamlabsOBSService.cs:line 191    at MixItUp.Overlay.OverlayWebServer.<Initialize>d__13.MoveNext() in S:\Code\mixer-mixitup\MixItUp.Desktop\Services\OverlayWebServer.cs:line 83