System.NotSupportedException: This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.    at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)    at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)    at System.Collections.ObjectModel.ObservableCollection`1.ClearItems()    at System.Collections.ObjectModel.Collection`1.Clear()    at MixItUp.Base.ViewModel.Controls.MainControls.RedemptionStoreMainControlViewModel.Refresh()    at MixItUp.Base.ViewModel.Controls.MainControls.RedemptionStoreMainControlViewModel.GlobalEvents_OnRedemptionStorePurchasesUpdated(Object sender, EventArgs e)    at MixItUp.Base.Util.GlobalEvents.RedemptionStorePurchasesUpdated()    at MixItUp.Base.Model.Currency.RedemptionStorePurchaseModel.<Redeem>d__30.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)    at MixItUp.Base.Model.Currency.RedemptionStorePurchaseModel.<Purchase>d__2.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)    at MixItUp.Base.Services.ChatService.<AddMessage>d__55.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at MixItUp.Base.Services.ChatService.<TwitchChatService_OnMessageOccurred>d__63.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)    at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()    at System.Threading.ThreadPoolWorkQueue.Dispatch()    at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()    at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)    at System.Environment.get_StackTrace()    at MixItUp.WPF.App.HandleCrash(Exception ex) in S:\Code\mixer-mixitup\MixItUp.WPF\App.xaml.cs:line 199    at MixItUp.WPF.App.CurrentDomain_UnhandledException(Object sender, UnhandledExceptionEventArgs e) in S:\Code\mixer-mixitup\MixItUp.WPF\App.xaml.cs:line 178    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)    at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()    at System.Threading.ThreadPoolWorkQueue.Dispatch()    at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()