System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.    at System.Windows.Threading.Dispatcher.VerifyAccess()    at System.Windows.DependencyObject.GetValue(DependencyProperty dp)    at System.Windows.FrameworkElement.get_ContextMenu()    at MixItUp.WPF.Controls.Chat.ChatListControl.ViewModel_ContextMenuCommandsChanged(Object sender, EventArgs e) in S:\Code\mixer-mixitup\MixItUp.WPF\Controls\Chat\ChatListControl.xaml.cs:line 121    at System.EventHandler.Invoke(Object sender, EventArgs e)    at MixItUp.Base.ViewModel.Controls.Chat.ChatListControlViewModel.Chat_ChatCommandsReprocessed(Object sender, EventArgs e)    at System.EventHandler.Invoke(Object sender, EventArgs e)    at MixItUp.Base.Services.ChatService.RebuildCommandTriggers()    at MixItUp.Base.Commands.AddCommandChatCommand.<>c.<<-ctor>b__0_0>d.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at MixItUp.Base.Commands.CustomAction.<PerformInternal>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at MixItUp.Base.Actions.ActionBase.<>c__DisplayClass15_0.<<Perform>b__0>d.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at StreamingClient.Base.Util.SemaphoreSlimExtensions.<WaitAndRelease>d__0.MoveNext()