System.IO.IOException: The process cannot access the file 'C:\Users\Danni\AppData\Local\MixItUp\Settings\c566b4dd-ced8-4e5c-a224-ea45b8127f98.db3' because it is being used by another process.    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)    at System.IO.File.InternalDelete(String path, Boolean checkHost)    at System.IO.File.Delete(String path)    at MixItUp.Base.Services.SettingsService.<GetAllSettings>d__2.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at MixItUp.WPF.LoginWindow.<OnLoaded>d__4.MoveNext() in S:\Code\mixer-mixitup\MixItUp.WPF\LoginWindow.xaml.cs:line 52 --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at MixItUp.WPF.Windows.LoadingWindowBase.<<LoadingWindowBase_Loaded>b__16_0>d.MoveNext() in S:\Code\mixer-mixitup\MixItUp.WPF\Windows\LoadingWindowBase.cs:line 114 --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at MixItUp.WPF.Windows.LoadingWindowBase.<RunAsyncOperation>d__9.MoveNext() in S:\Code\mixer-mixitup\MixItUp.WPF\Windows\LoadingWindowBase.cs:line 44 --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at MixItUp.WPF.Windows.LoadingWindowBase.<LoadingWindowBase_Loaded>d__16.MoveNext() in S:\Code\mixer-mixitup\MixItUp.WPF\Windows\LoadingWindowBase.cs:line 112 --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)